-- Player Passing Type Stats
CREATE TABLE IF NOT EXISTS player_passing_type_stats (
    id SERIAL PRIMARY KEY,
    season_end_year INTEGER NOT NULL,
    squad TEXT NOT NULL,
    comp TEXT NOT NULL,
    player TEXT NOT NULL,
    nation TEXT,
    pos TEXT,
    age INTEGER,
    born INTEGER,
    mins_per_90 REAL,
    att INTEGER,
    live_pass INTEGER,
    dead_pass INTEGER,
    fk_pass INTEGER,
    tb_pass INTEGER,
    sw_pass INTEGER,
    crs_pass INTEGER,
    ti_pass INTEGER,
    ck_pass INTEGER,
    in_corner INTEGER,
    out_corner INTEGER,
    str_corner INTEGER,
    cmp_outcomes INTEGER,
    off_outcomes INTEGER,
    blocks_outcomes INTEGER,
    url TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Team Passing Type Stats
CREATE TABLE IF NOT EXISTS team_passing_type_stats (
    id SERIAL PRIMARY KEY,
    season_end_year INTEGER NOT NULL,
    squad TEXT NOT NULL,
    comp TEXT NOT NULL,
    team_or_opponent TEXT NOT NULL,
    num_players INTEGER,
    mins_per_90 REAL,
    att INTEGER,
    live_pass INTEGER,
    dead_pass INTEGER,
    fk_pass INTEGER,
    tb_pass INTEGER,
    sw_pass INTEGER,
    crs_pass INTEGER,
    ti_pass INTEGER,
    ck_pass INTEGER,
    in_corner INTEGER,
    out_corner INTEGER,
    str_corner INTEGER,
    cmp_outcomes INTEGER,
    off_outcomes INTEGER,
    blocks_outcomes INTEGER,
    url TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);
